@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card shadow-sm">
                <div class="card-header bg-white py-3">
                    <h5 class="mb-0 fw-bold">Add New Employee</h5>
                </div>
                <div class="card-body p-4">
                    <form action="{{ route('admin.employees.store') }}" method="POST">
                        @csrf

                        <h6 class="text-uppercase text-muted fw-bold small mb-3">Account Details</h6>
                        <div class="row g-3 mb-4">
                            <div class="col-md-6">
                                <label class="form-label">Full Name</label>
                                <input type="text" name="name" class="form-control" required>
                            </div>
                            <div class="col-md-6">
                                <label class="form-label">Email Address</label>
                                <input type="email" name="email" class="form-control" required>
                            </div>
                            <div class="col-md-6">
                                <label class="form-label">Password</label>
                                <input type="password" name="password" class="form-control" placeholder="Default Password"
                                    required>
                            </div>
                        </div>

                        <h6 class="text-uppercase text-muted fw-bold small mb-3">Professional Details</h6>
                        <div class="row g-3 mb-4">
                            <div class="col-md-4">
                                <label class="form-label">Employee ID</label>
                                <input type="text" name="employee_id" class="form-control bg-light"
                                    placeholder="Auto-generated by System" readonly>
                            </div>
                            <div class="col-md-4">
                                <label class="form-label">Department</label>
                                <select name="department" class="form-select" required>
                                    <option value="">Select Department</option>
                                    <option value="HR">HR</option>
                                    <option value="IT">IT</option>
                                    <option value="Finance">Finance</option>
                                    <option value="Sales">Sales</option>
                                    <option value="Operations">Operations</option>
                                </select>
                            </div>
                            <div class="col-md-4">
                                <label class="form-label">Designation</label>
                                <select name="designation" class="form-select" required>
                                    <option value="">Select Designation</option>
                                    @foreach($designations as $d)
                                        <option value="{{ $d->name }}">{{ $d->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-md-6">
                                <label class="form-label">Joining Date</label>
                                <input type="date" name="joining_date" class="form-control" required>
                            </div>
                            <div class="col-md-6">
                                <label class="form-label">Base Salary</label>
                                <div class="input-group">
                                    <span class="input-group-text">$</span>
                                    <input type="number" name="base_salary" class="form-control" required>
                                </div>
                            </div>
                        </div>

                        <h6 class="text-uppercase text-muted fw-bold small mb-3">Personal Details</h6>
                        <div class="row g-3 mb-4">
                            <div class="col-md-6">
                                <label class="form-label">Phone Start</label>
                                <input type="text" name="phone" class="form-control">
                            </div>
                            <div class="col-md-6">
                                <label class="form-label">Address</label>
                                <input type="text" name="address" class="form-control">
                            </div>
                        </div>

                        <div class="d-flex justify-content-end gap-2">
                            <a href="{{ route('admin.employees.index') }}" class="btn btn-light">Cancel</a>
                            <button type="submit" class="btn btn-primary px-4">Create Employee</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection